export * from './Admin';
export * from './Contact';
export * from './Home';
export * from './Register';
export * from './Login';
export * from './ProductDetails';
export * from './Shopping';
export * from './User';
export * from './LandingPage';